M48
; DRILL file {KiCad 8.0.1-8.0.1-1~ubuntu22.04.1} date 2024-03-31T12:30:23+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-03-31T12:30:23+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1-8.0.1-1~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X80.0Y-50.0
X80.0Y-140.0
X213.0Y-50.0
X213.0Y-140.0
M30
